#ifndef DATABASEHANDLER_GLOBAL_H
#define DATABASEHANDLER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATABASEHANDLER_LIBRARY)
#  define DATABASEHANDLERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATABASEHANDLERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATABASEHANDLER_GLOBAL_H
